FROM mcr.microsoft.com/playwright:v1.57.0-noble

# Set working directory
WORKDIR /app

# Copy package.json & install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# Install Playwright browsers
RUN npx playwright install --with-deps

# Copy the test code
COPY playwright.config.ts .
COPY ./tests/e2e ./tests/e2e

# run npm playwright test
CMD ["npx", "playwright", "test"]

