services:
  app:
    build: .
    ports:
      - "3000:3000"

  db:
    image: postgres

  e2e:
    image: mcr.microsoft.com/playwright:v1.57.0-noble
    command: npx playwright test
    profiles: ["e2e"]
    depends_on:
      - app
