name: CI with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  full-test-with-docker-compose:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 2. Ensure Docker Compose is available
      - name: Check Docker Compose
        run: docker compose version

      # 3. Start all docker containers in background
      - name: Docker Compose in Background
        run: docker compose up -d

      # 4. Run full test
      - name: Run Full Test
        run: npm run test:full

      # 5. Tear down
      - name: Tear Down Docker Compose
        run: docker compose down -v
